name: secure_storage
description: |
  Secure Storage: Encrypted data store optionally secured by biometric lock with support
  for iOS, Android, MacOS. Partial support for Linux, Windows and web (localStorage).
version: 5.1.1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  logging: ">=1.0.0 <2.0.0"
  plugin_platform_interface: ">=2.0.0 <3.0.0"

  ffi: '>=1.0.0 <3.0.0'
  win32: '>=2.0.0 <6.0.0'
  web: ">=0.5.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: io.blockshake.secure_storage
        pluginClass: SecureStoragePlugin
      ios:
        pluginClass: SecureStoragePlugin
      web:
        pluginClass: SecureStoragePluginWeb
        fileName: src/secure_storage_web.dart

topics:
  - biometrics
  - encryption
  - storage
  - security
  - secure-storage
screenshots:
  - description: 'Face ID on iPhone'
    path: doc/screenshot_ios.png
